baseurl = "https://neuromaternal.github.io/"
title = "NeuroMaternal"
languageCode = "es-es"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "es"
SectionPagesMenu = "main"
Paginate = 4 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.es]
    title = "NeuroMaternal"
    weight = 1
    contentDir = "content/es"
 # [languages.fr]
 #  title = "NeuroMaternal"
 #  weight = 2
 #   contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "Grupo de investigación en neurociencia acerca de los cambios cerebrales asociados al embarazo y la maternidad"
  facebook = ""
  twitter = ""
  instagram = "https://www.instagram.com/neuro.maternal/?hl=es"
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/imagen_BEMOTHER1_jpeg.jpeg"
  recent_posts_number = 0
